apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard0-service
  labels:
    name: mongodb-shard0
spec:
  ports:
  - port: 27019
    targetPort: 27019
  clusterIP: None
  selector:
    role: mongodb-shard0
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod-shard0
spec:
  serviceName: mongodb-shard0-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shard0
        tier: maindb
        replicaset: shard0
    spec:
      nodeSelector:
        kubernetes.io/hostname: wxec0052
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - shard0
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
        - name: datadir
          hostPath:
            path: /mnt/viid/mongodb/shard0/db
            type: Directory 
        - name: configdir
          hostPath:
            path: /mnt/viid/mongodb/shard0/configdb
            type: Directory               
      containers:
        - name: mongod-shard0-container
          image: mongo:3.6.4-jessie
          command:
            - "mongod"
            - "--port"
            - "27019"
            - "--wiredTigerCacheSizeGB"
            - "20"
            - "--bind_ip"
            - "0.0.0.0"
            - "--shardsvr"
            - "--replSet"
            - "shard0"
          # resources:
          #   requests:
          #     cpu: 0.25
          #     memory: 512Mi
          ports:
            - containerPort: 27019
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: datadir
              mountPath: /data/db
            - name: configdir
              mountPath: /data/configdb   
