version: '2'
services:
   ## Config Servers
  config1:
    image: mongo:3.6.4-jessie
    command: mongod --port 27018 --configsvr --wiredTigerCacheSizeGB 1 --replSet configserver
    restart: always
    network_mode: host
    ports:
      - "27018"  
    volumes:
      - ./scripts:/scripts
      - /yitu/hdd1/viid/qinyujia/mongodb/config1/db:/data/db
      - /yitu/hdd1/viid/qinyujia/mongodb/config1/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./keyfile:/keyfile
    extra_hosts:
      - mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:10.40.80.146
      - mongod-shard0-0.mongodb-shard0-service.default.svc.cluster.local:10.40.80.146
      - mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:10.40.80.148
      - mongod-shard1-0.mongodb-shard1-service.default.svc.cluster.local:10.40.80.148
  ## Shards
  shard1:
    image: mongo:3.6.4-jessie
    command: mongod --port 27019 --shardsvr --wiredTigerCacheSizeGB 20 --replSet shard1
    restart: always
    network_mode: host
    ports:
      - "27019"
    volumes:
      - ./scripts:/scripts
      - /yitu/hdd1/viid/qinyujia/mongodb/shard1/db:/data/db
      - /yitu/hdd1/viid/qinyujia/mongodb/shard1/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./keyfile:/keyfile
    extra_hosts:
      - mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:10.40.80.146
      - mongod-shard0-0.mongodb-shard0-service.default.svc.cluster.local:10.40.80.146
      - mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:10.40.80.148
      - mongod-shard1-0.mongodb-shard1-service.default.svc.cluster.local:10.40.80.148
  ## Router
  router1:
    image: mongo:3.6.4-jessie
#    command: mongos --port 37017 --configdb configserver/config0:37018,config1:37018 --bind_ip_all
    command: mongos --port 27017  --configdb configserver/mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:27018,mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:27018 --bind_ip_all
    restart: always
    network_mode: host
    ports:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /yitu/hdd1/viid/qinyujia/mongodb/router1/db:/data/db
      - /yitu/hdd1/viid/qinyujia/mongodb/router1/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./keyfile:/keyfile
    extra_hosts:
      - mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:10.40.80.146
      - mongod-shard0-0.mongodb-shard0-service.default.svc.cluster.local:10.40.80.146
      - mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:10.40.80.148
      - mongod-shard1-0.mongodb-shard1-service.default.svc.cluster.local:10.40.80.148
