version: '2'
services:
   ## Config Servers
  config0:
    image: mongo:3.6.4-jessie
    command: mongod --port 27018 --configsvr --wiredTigerCacheSizeGB 1 --replSet configserver
    restart: always
    network_mode: host
    ports:
      - "27018"  
    volumes:
      - ./scripts:/scripts
      - /yitu/hdd1/viid/qinyujia/mongodb/config0/db:/data/db
      - /yitu/hdd1/viid/qinyujia/mongodb/config0/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./keyfile:/keyfile
    extra_hosts:
      - mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:10.40.80.146
      - mongod-shard0-0.mongodb-shard0-service.default.svc.cluster.local:10.40.80.146
      - mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:10.40.80.148
      - mongod-shard1-0.mongodb-shard1-service.default.svc.cluster.local:10.40.80.148
  ## Shards
  shard0:
    image: mongo:3.6.4-jessie
    command: mongod --port 27019 --shardsvr --wiredTigerCacheSizeGB 22 --replSet shard0
    restart: always
    network_mode: host
    ports:
      - "27019"
    volumes:
      - ./scripts:/scripts
      - /yitu/hdd1/viid/qinyujia/mongodb/shard0/db:/data/db
      - /yitu/hdd1/viid/qinyujia/mongodb/shard0/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./keyfile:/keyfile
    extra_hosts:
      - mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:10.40.80.146
      - mongod-shard0-0.mongodb-shard0-service.default.svc.cluster.local:10.40.80.146
      - mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:10.40.80.148
      - mongod-shard1-0.mongodb-shard1-service.default.svc.cluster.local:10.40.80.148
  ## Router
  router0:
    image: mongo:3.6.4-jessie
    command: mongos --port 27017 --configdb configserver/mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:27018,mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:27018 --bind_ip_all
    restart: always
    network_mode: host
    ports:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /yitu/hdd1/viid/qinyujia/mongodb/router0/db:/data/db
      - /yitu/hdd1/viid/qinyujia/mongodb/router0/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./keyfile:/keyfile
    extra_hosts:
      - mongod-configdb-0.mongodb-configdb-service.default.svc.cluster.local:10.40.80.146
      - mongod-shard0-0.mongodb-shard0-service.default.svc.cluster.local:10.40.80.146
      - mongod-configdb-1.mongodb-configdb-service.default.svc.cluster.local:10.40.80.148
      - mongod-shard1-0.mongodb-shard1-service.default.svc.cluster.local:10.40.80.148
